version: "3"
volumes:
  prometheus_data: {}
  
services:

  techefx-eureka-naming:
    image: techefx-eureka-naming-server
    ports:
      - "8761:8761"
    networks:
      - test-network

  techefx-product-stock:
    image: techefx-product-stock-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-naming:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8800:8800"
    depends_on:
      - techefx-eureka-naming
    networks:
      - test-network

  techefx-product-enquiry:
    image: techefx-product-enquiry-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-naming:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
    ports:
      - "8700:8700"
    depends_on:
      - techefx-product-stock
    networks:
      - test-network

  techefx-spring-cloud-api-gateway:
    image: techefx-spring-cloud-api-gateway-service
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://techefx-eureka-naming:8761/eureka
        -DZIPKIN_SERVER=http://zipkin:9411/
 #       -DENQUIRY_SERVICE=http://techefx-product-enquiry:9700/
    ports:
      - "8900:8900"
    depends_on:
      - techefx-eureka-naming
      - techefx-product-enquiry
      - techefx-product-stock
    networks:
      - test-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/:/etc/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    depends_on:
      - techefx-product-stock
    networks:
      - test-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - test-network

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    depends_on:
      - techefx-eureka-naming
    networks:
      - test-network

networks:
  test-network:
